DELETE FROM book;
DELETE FROM editorial;

ALTER SEQUENCE book_sequence RESTART WITH 1;
ALTER SEQUENCE editorial_sequence RESTART WITH 1;

INSERT INTO EDITORIAL (ID,NAME)
VALUES (100,'Editorial100');

INSERT INTO BOOK (ID,TITLE,AUTHOR,PUBLISH,PAGES,DESCRIPTION,ID_EDITORIAL)
VALUES (200,'Libro200','Autor200',TO_DATE('12/12/2012', 'DD/MM/YYYY'),270,'Descripcion del libro 200',100);